services:
  - type: web
    name: istqbquiz
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DOTNET_RUNNING_IN_CONTAINER
        value: true
