name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main  # wenn du auf main pushst, wird deploy gestartet

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # passt zu deinem Projekt

      - name: Publish Blazor WASM
        run: dotnet publish ./Client/IstqbQuiz.Client.csproj -c Release -o release

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Client/release/wwwroot
          publish_branch: gh-pages
