name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # oder dein Hauptbranch

permissions:
  contents: write  # ✅ gibt der Action Schreibrechte

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Server/IstqbQuiz.Server.csproj

      - name: Publish Blazor
        run: dotnet publish ./Server/IstqbQuiz.Server.csproj -c Release -o release --nologo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
