name: Deploy Blazor PWA to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # 3. Restore Dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Publish Blazor WASM (Client-Projekt)
      - name: Publish Blazor WebAssembly
        run: dotnet publish ./Client/IstqbQuiz.Client.csproj -c Release -o release

      # 5. Erstelle 404.html aus index.html
      - name: Create 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # 6. Deploy zu gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
          publish_branch: gh-pages
