name: Deploy Blazor PWA to GitHub Pages

on:
  push:
    branches:
      - main  # Aktion wird nur bei Push auf main ausgeführt

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Publish Blazor WebAssembly
        run: dotnet publish ./Client/IstqbQuiz.Client.csproj -c Release -o release --nologo

      - name: Prepare for GitHub Pages
        run: |
          cd release/wwwroot
          touch .nojekyll  # wichtig für GitHub Pages
          echo "✅ Build erfolgreich vorbereitet!"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
          publish_branch: gh-pages
