name: .NET Tests with Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test with coverage
        run: >
          dotnet test --no-build --configuration Release
          /p:CollectCoverage=true
          /p:CoverletOutput=ISTQB_UnitTest/TestResults/
          /p:CoverletOutputFormat=cobertura

      - name: List TestResults folder
        run: ls -R ISTQB_UnitTest/TestResults || echo "No TestResults folder found"

      - name: Generate coverage report
        run: >
          reportgenerator
          -reports:ISTQB_UnitTest/TestResults/coverage.cobertura.xml
          -targetdir:CoverageReport
          -reporttypes:Html

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: CoverageReport

      - name: Deploy coverage report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./CoverageReport
